[project]
name = "hatespeech-detection"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.1",
    "numpy>=2.2.5",
    "pandas>=2.2.3",
]

[tool.uv.workspace]
members = [
    "llm_detection",
    "vilio",
]
